--
-- DEV Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "SF_GENERAL_ADMIN";
GRANT ROLE "SF_GENERAL_ADMIN" TO ROLE SYSADMIN;
USE ROLE SYSADMIN;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE "SF_GENERAL_ADMIN";
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE "SF_GENERAL_ADMIN";