--
-- DEV Environment
--

USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS "FR_ANALYST_DEV";
GRANT ROLE "FR_ANALYST_DEV" TO ROLE "SF_GENERAL_ADMIN";
CREATE ROLE IF NOT EXISTS "FR_DEVELOPER_DEV";
GRANT ROLE "FR_DEVELOPER_DEV" TO ROLE "SF_GENERAL_ADMIN";
CREATE ROLE IF NOT EXISTS "FR_SR_ETL_MATILLION_DEV";
GRANT ROLE "FR_SR_ETL_MATILLION_DEV" TO ROLE "SF_GENERAL_ADMIN";
CREATE ROLE IF NOT EXISTS "FR_TEAM_LEAD_DEV";
GRANT ROLE "FR_TEAM_LEAD_DEV" TO ROLE "SF_GENERAL_ADMIN";